language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: gcs
  access_key_id: GOOG6XNS2QINHV4C7ESV6D3H
  secret_access_key:
    secure: yFXBExsNNrx/N3iG3uyTHu7j0Zzgj+EuTeqcSDEL
  skip_cleanup: true
  bucket: react-poc-gcp
  local-dir: ./build
  upload-dir: build
  detect_encoding: true
  cache_control: no-cache
  on:
    repo: eselopio/gcp-react-todo
  acl: public-read