runtime: python27
api_version: 1
threadsafe: true
skip_files:
- ^node_modules/(?!node\.js$).*
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build